### ISSUE TITLE
As an author, I want to post posts to my “stream”

### ISSUE THREAD

**Issue by XuechunHou** [AustinGrey/cmput404-group-project#23]

**Comment by AustinGrey** [comment]
@phoebebai Is it you or @DylanAlcock working on the front end for streams? This is a top priority story and I want to make sure it's clear who I need to work with.

**Comment by DylanAlcock** [comment]
I believe Phoebe is working on setting up the view for streams, but I think this is more towards making a post, as all an authors posts should be on their stream if I'm not mistaken. So this should be me. @AustinGrey

**Comment by AustinGrey** [comment]
Okay, I'll work with you dylan to make sure we can post, and I'll work with pheobe to make sure she has the endpoint she needs to get the stream up. As such I'm adding pheobe to the story
